src/.design/homer/Homer_Full_Version_ASP_MVC/Homer_MVC/Controllers/AppViewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Homer_MVC.Controllers
{
    public class AppViewsController : Controller
    {

        public ActionResult Contacts()
        {
            return View();
        }

        public ActionResult Projects()
        {
            return View();
        }

        public ActionResult SocialBoard()
        {
            return View();
        }

        public ActionResult Timeline()
        {
            return View();
        }

        public ActionResult ProfilePage()
        {
            return View();
        }

        public ActionResult Blog()
        {
            return View();
        }

        public ActionResult BlogArticle()
        {
            return View();
        }

        public ActionResult Forum()
        {
            return View();
        }

        public ActionResult ForumDetails()
        {
            return View();
        }

        public ActionResult Calendar()
        {
            return View();
        }

        public ActionResult ProjectDetail()
        {
            return View();
        }

        public ActionResult Mailbox()
        {
            return View();
        }

        public ActionResult Gallery()
        {
            return View();
        }

        public ActionResult FileManager()
        {
            return View();
        }

        public ActionResult Search()
        {
            return View();
        }

        public ActionResult Invoice()
        {
            return View();
        }

        public ActionResult ChatView()
        {
            return View();
        }

        public ActionResult AppPlans()
        {
            return View();
        }

        public ActionResult Faq()
        {
            return View();
        }

        public ActionResult Notes()
        {
            return View();
        }

        public ActionResult EmailCompose()
        {
            return View();
        }

        public ActionResult EmailView()
        {
            return View();
        }


    }
}

src/.design/homer/Homer_Full_Version_ASP_MVC/Homer_MVC/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Mvc.Html;

namespace Homer_MVC.Controllers
{
    public class DashboardController : Controller
    {

        public ActionResult Index()
        {
            return View();
        }

    }
}

src/.design/homer/Homer_Full_Version_ASP_MVC/Homer_MVC/Views/AppViews/Contacts.cshtml
@{
    ViewBag.Title = "Contacts";
}

<div class="normalheader transition animated fadeIn">
    <div class="hpanel">
        <div class="panel-body">
            <a class="small-header-action" href="">
                <div class="clip-header">
                    <i class="fa fa-arrow-up"></i>
                </div>
            </a>

            <div id="hbreadcrumb" class="pull-right m-t-lg">
                <ol class="hbreadcrumb breadcrumb">
                    <li><a href="@Url.Action("Index", "Dashboard")">Dashboard</a></li>
                    <li>
                        <span>App views</span>
                    </li>
                    <li class="active">
                        <span>Contacts</span>
                    </li>
                </ol>
            </div>
            <h2 class="font-light m-b-xs">
                Contacts
            </h2>
            <small>Show users list in nice and color panels</small>
        </div>
    </div>
</div>

<div class="content animate-panel">

    <div class="row">
        <div class="col-lg-3">
            <div class="hpanel hgreen contact-panel">
                <div class="panel-body">
                    <span class="label label-success pull-right">NEW</span>
                    <img alt="logo" class="img-circle m-b" src="~/Images/profile.jpg">
                    <h3><a href=""> Bradly Danforth </a></h3>
                    <div class="text-muted font-bold m-b-xs">California, LA</div>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum tincidunt est vitae ultrices accumsan.
                    </p>
                </div>
                <div class="panel-footer contact-footer">
                    <div class="row">
                        <div class="col-md-4 border-right"> <div class="contact-stat"><span>Projects: </span> <strong>200</strong></div> </div>
                        <div class="col-md-4 border-right"> <div class="contact-stat"><span>Messages: </span> <strong>300</strong></div> </div>
                        <div class="col-md-4"> <div class="contact-stat"><span>Views: </span> <strong>400</strong></div> </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-3">
            <div class="hpanel hyellow contact-panel">
                <div class="panel-body">
                    <img alt="logo" class="img-circle m-b" src="~/Images/a4.jpg">
                    <h3><a href=""> Tangela Sternberg </a></h3>
                    <div class="text-muted font-bold m-b-xs">California, LA</div>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum tincidunt est vitae ultrices accumsan.
                    </p>
                </div>
                <div class="panel-footer contact-footer">
                    <div class="row">
                        <div class="col-md-4 border-right"> <div class="contact-stat"><span>Projects: </span> <strong>200</strong></div> </div>
                        <div class="col-md-4 border-right"> <div class="contact-stat"><span>Messages: </span> <strong>300</strong></div> </div>
                        <div class="col-md-4"> <div class="contact-stat"><span>Views: </span> <strong>400</strong></div> </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-3">
            <div class="hpanel hviolet contact-panel">
                <div class="panel-body">
                    <img alt="logo" class="img-circle m-b" src="~/Images/a2.jpg">
                    <h3><a href=""> Claud Vogan </a></h3>
                    <div class="text-muted font-bold m-b-xs">California, LA</div>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum tincidunt est vitae ultrices accumsan.
                    </p>
                </div>
                <div class="panel-footer contact-footer">
                    <div class="row">
                        <div class="col-md-4 border-right"> <div class="contact-stat"><span>Projects: </span> <strong>200</strong></div> </div>
                        <div class="col-md-4 border-right"> <div class="contact-stat"><span>Messages: </span> <strong>300</strong></div> </div>
                        <div class="col-md-4"> <div class="contact-stat"><span>Views: </span> <strong>400</strong></div> </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-3">
            <div class="hpanel hblue contact-panel">
                <div class="panel-body">
                    <img alt="logo" class="img-circle m-b" src="~/Images/a3.jpg">
                    <h3><a href=""> Valda Purdy </a></h3>
                    <div class="text-muted font-bold m-b-xs">California, LA</div>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum tincidunt est vitae ultrices accumsan.
                    </p>
                </div>
                <div class="panel-footer contact-footer">
                    <div class="row">
                        <div class="col-md-4 border-right"> <div class="contact-stat"><span>Projects: </span> <strong>200</strong></div> </div>
                        <div class="col-md-4 border-right"> <div class="contact-stat"><span>Messages: </span> <strong>300</strong></div> </div>
                        <div class="col-md-4"> <div class="contact-stat"><span>Views: </span> <strong>400</strong></div> </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-3">
            <div class="hpanel hblue contact-panel">
                <div class="panel-body">
                    <img alt="logo" class="img-circle m-b" src="~/Images/a9.jpg">
                    <h3><a href="">Max Simson</a></h3>
                    <div class="text-muted font-bold m-b-xs">California, LA</div>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum tincidunt est vitae ultrices accumsan.
                    </p>
                </div>
                <div class="panel-footer contact-footer">
                    <div class="row">
                        <div class="col-md-4 border-right"> <div class="contact-stat"><span>Projects: </span> <strong>200</strong></div> </div>
                        <div class="col-md-4 border-right"> <div class="contact-stat"><span>Messages: </span> <strong>300</strong></div> </div>
                        <div class="col-md-4"> <div class="contact-stat"><span>Views: </span> <strong>400</strong></div> </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-3">
            <div class="hpanel hgreen contact-panel">
                <div class="panel-body">
                    <img alt="logo" class="img-circle m-b" src="~/Images/a5.jpg">
                    <h3><a href="">Max Simson</a></h3>
                    <div class="text-muted font-bold m-b-xs">California, LA</div>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum tincidunt est vitae ultrices accumsan.
                    </p>
                </div>
                <div class="panel-footer contact-footer">
                    <div class="row">
                        <div class="col-md-4 border-right"> <div class="contact-stat"><span>Projects: </span> <strong>200</strong></div> </div>
                        <div class="col-md-4 border-right"> <div class="contact-stat"><span>Messages: </span> <strong>300</strong></div> </div>
                        <div class="col-md-4"> <div class="contact-stat"><span>Views: </span> <strong>400</strong></div> </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-3">
            <div class="hpanel hyellow contact-panel">
                <div class="panel-body">
                    <span class="label label-warning pull-right">SPECIAL</span>
                    <img alt="logo" class="img-circle m-b" src="~/Images/a6.jpg">
                    <h3><a href="">Max Simson</a></h3>
                    <div class="text-muted font-bold m-b-xs">California, LA</div>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum tincidunt est vitae ultrices accumsan.
                    </p>
                </div>
                <div class="panel-footer contact-footer">
                    <div class="row">
                        <div class="col-md-4 border-right"> <div class="contact-stat"><span>Projects: </span> <strong>200</strong></div> </div>
                        <div class="col-md-4 border-right"> <div class="contact-stat"><span>Messages: </span> <strong>300</strong></div> </div>
                        <div class="col-md-4"> <div class="contact-stat"><span>Views: </span> <strong>400</strong></div> </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-3">
            <div class="hpanel hred contact-panel">
                <div class="panel-body">
                    <img alt="logo" class="img-circle m-b" src="~/Images/a7.jpg">
                    <h3><a href="">Max Simson</a></h3>
                    <div class="text-muted font-bold m-b-xs">California, LA</div>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum tincidunt est vitae ultrices accumsan.
                    </p>
                </div>
                <div class="panel-footer contact-footer">
                    <div class="row">
                        <div class="col-md-4 border-right"> <div class="contact-stat"><span>Projects: </span> <strong>200</strong></div> </div>
                        <div class="col-md-4 border-right"> <div class="contact-stat"><span>Messages: </span> <strong>300</strong></div> </div>
                        <div class="col-md-4"> <div class="contact-stat"><span>Views: </span> <strong>400</strong></div> </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

src/.design/homer/Homer_Full_Version_ASP_MVC/Homer_MVC/Views/AppViews/Forum.cshtml
@{
    ViewBag.Title = "Forum";
}

<div class="normalheader transition animated fadeIn">
    <div class="hpanel">
        <div class="panel-body">
            <a class="small-header-action" href="">
                <div class="clip-header">
                    <i class="fa fa-arrow-up"></i>
                </div>
            </a>

            <div id="hbreadcrumb" class="pull-right m-t-lg">
                <ol class="hbreadcrumb breadcrumb">
                    <li><a href="@Url.Action("Index", "Dashboard")">Dashboard</a></li>
                    <li>
                        <span>App views</span>
                    </li>
                    <li class="active">
                        <span>Forum</span>
                    </li>
                </ol>
            </div>
            <h2 class="font-light m-b-xs">
                Forum
            </h2>
            <small>Topics board for forum page.</small>
        </div>
    </div>
</div>

<div class="content animate-panel">



    <div class="row">
        <div class="col-lg-12">

            <div class="hpanel">
                <div class="panel-body">
                    <div class="text-muted small pull-right text-right">
                        Proin eu tempus tortor, vitae bibendum est. Nam placerat hendrerit rhoncus<br />
                        Last modyfication by: <span class="font-bold">Mike Smith</span>
                        21.03.2015, 06:45 pm
                    </div>
                    <div class="form-inline">
                        Search topic: <input class="form-control" type="text">
                    </div>

                </div>

            </div>


            <div class="hpanel forum-box">

                <div class="panel-heading">
                    <span class="pull-right">
                        <i class="fa fa-clock-o"> </i> Last modification: 10.12.2015, 10:22 am
                    </span>
                    General topics
                </div>

                <div class="panel-body">
                    <div class="row">

                        <div class="col-md-10 forum-heading">

                            <span class="label label-success pull-left">Special</span>
                            <a href="@Url.Action("ForumDetails", "AppViews")"><h4> General Discussion</h4></a>
                            <div class="desc">Suspendisse egestas risus quis sem ultricies venenatis. Phasellus maximus tortor ut augue accumsan, sed posuere dolor tincidunt. In hac habitasse platea dictumst.</div>
                        </div>
                        <div class="col-md-1 forum-info">
                            <span class="number"> 4780 </span>
                            <small>Views</small>
                        </div>
                        <div class="col-md-1 forum-info">
                            <span class="number"> 150 </span>
                            <small>Posts</small>
                        </div>
                    </div>
                </div>

                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-10 forum-heading">
                            <a href="@Url.Action("ForumDetails", "AppViews")"><h4>Introductions</h4></a>
                            <div class="desc">Mauris feugiat ante vitae euismod vestibulum. Suspendisse id ullamcorper odio, ut tristique ante. In scelerisque dolor in mi condimentum consequat.</div>
                        </div>
                        <div class="col-md-1 forum-info">
                            <span class="number"> 260 </span>
                            <small>Views</small>
                        </div>
                        <div class="col-md-1 forum-info">
                            <span class="number"> 149 </span>
                            <small>Posts</small>
                        </div>
                    </div>
                </div>

            </div>

            <div class="hpanel forum-box">

                <div class="panel-heading">
                    <span class="pull-right">
                        <i class="fa fa-clock-o"> </i> Last modification: 11.10.2015, 08:10 am
                    </span>
                    Nunc eu luctus neque.
                </div>

                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-10 forum-heading">
                            <span class="label label-warning pull-left">New</span>
                            <a href="@Url.Action("ForumDetails", "AppViews")">
                                <h4>Morbi aliquam aliquam</h4>
                            </a>
                            <div class="desc">Morbi aliquam aliquam erat, id iaculis dui maximus vel. Curabitur dolor leo, tempus sit amet rutrum nec, luctus vel nisl. Nam sollicitudin quam non arcu faucibus, id mattis lacus interdum. Nam eleifend sodales ante sed pharetra. Integer cursus dapibus fringilla.</div>
                        </div>
                        <div class="col-md-1 forum-info">
                            <span class="number"> 2451 </span>
                            <small>Views</small>
                        </div>
                        <div class="col-md-1 forum-info">
                            <span class="number"> 100 </span>
                            <small>Posts</small>
                        </div>
                    </div>
                </div>

                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-10 forum-heading">
                            <span class="label label-warning pull-left">New</span>
                            <a href="@Url.Action("ForumDetails", "AppViews")"><h4>Quisque ultrices </h4></a>
                            <div class="desc">Vestibulum scelerisque semper ligula ac consectetur. Proin tincidunt dui ac quam mollis eleifend.</div>
                        </div>
                        <div class="col-md-1 forum-info">
                            <span class="number"> 5699 </span>
                            <small>Views</small>
                        </div>
                        <div class="col-md-1 forum-info">
                            <span class="number"> 114 </span>
                            <small>Posts</small>
                        </div>
                    </div>
                </div>

            </div>

            <div class="hpanel forum-box">

                <div class="panel-heading">
                    <span class="pull-right">
                        <i class="fa fa-clock-o"> </i> Last modification: 01.03.2015, 11:10 am
                    </span>
                    Aenean vitae
                </div>

                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-10 forum-heading">
                            <a href="@Url.Action("ForumDetails", "AppViews")">
                                <h4>Pellentesque rhoncus </h4>
                            </a>
                            <div class="desc">Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. </div>
                        </div>
                        <div class="col-md-1 forum-info">
                            <span class="number"> 1200 </span>
                            <small>Views</small>
                        </div>
                        <div class="col-md-1 forum-info">
                            <span class="number"> 457 </span>
                            <small>Posts</small>
                        </div>
                    </div>
                </div>

                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-10 forum-heading">
                            <a href="@Url.Action("ForumDetails", "AppViews")"><h4>Sed iaculis vel libero</h4></a>
                            <div class="desc">Nam sollicitudin quam non arcu faucibus, id mattis lacus interdum. Nam eleifend sodales ante sed pharetra. Integer cursus dapibus fringilla. Maecenas volutpat dapibus vestibulum. Mauris ullamcorper nibh nec consectetur fermentum. </div>
                        </div>
                        <div class="col-md-1 forum-info">
                            <span class="number"> 460 </span>
                            <small>Views</small>
                        </div>
                        <div class="col-md-1 forum-info">
                            <span class="number"> 280 </span>
                            <small>Posts</small>
                        </div>
                    </div>
                </div>

                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-10 forum-heading">
                            <span class="label label-info pull-left">Latest</span>
                            <a href="@Url.Action("ForumDetails", "AppViews")"><h4>Mauris fermentum </h4></a>
                            <div class="desc">Aenean ornare lacus quis blandit posuere. Nulla porta lectus facilisis justo pharetra, nec varius felis sollicitudin.</div>
                        </div>
                        <div class="col-md-1 forum-info">
                            <span class="number"> 870 </span>
                            <small>Views</small>
                        </div>
                        <div class="col-md-1 forum-info">
                            <span class="number"> 621 </span>
                            <small>Posts</small>
                        </div>
                    </div>
                </div>

                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-10 forum-heading">
                            <a href="@Url.Action("ForumDetails", "AppViews")"><h4>Vivamus non lacus diam.</h4></a>
                            <div class="desc">Aenean quis nulla finibus, lobortis nunc sit amet, tempor ligula. Nunc pharetra, mauris aliquet mollis semper, libero eros mattis eros, sit amet semper elit libero in leo. In porttitor quam sit amet felis congue aliquam. Ut commodo aliquam consectetur. In hac habitasse platea dictumst.</div>
                        </div>
                        <div class="col-md-1 forum-info">
                            <span class="number"> 278 </span>
                            <small>Views</small>
                        </div>
                        <div class="col-md-1 forum-info">
                            <span class="number"> 455 </span>
                            <small>Posts</small>
                        </div>
                    </div>
                </div>

                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-10 forum-heading">
                            <a href="@Url.Action("ForumDetails", "AppViews")"><h4>Donec lacus dolor</h4></a>
                            <div class="desc">Nullam ipsum diam, tempus at pretium id, posuere rutrum urna. Sed et eros vitae magna condimentum semper sed vel enim. </div>
                        </div>
                        <div class="col-md-1 forum-info">
                            <span class="number"> 780 </span>
                            <small>Views</small>
                        </div>
                        <div class="col-md-1 forum-info">
                            <span class="number"> 120 </span>
                            <small>Posts</small>
                        </div>
                    </div>
                </div>

                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-10 forum-heading">
                            <a href="@Url.Action("ForumDetails", "AppViews")"><h4>Fusce sagittis</h4></a>
                            <div class="desc">Duis sed enim velit. In auctor porta lorem, nec viverra risus faucibus at. Nulla sagittis eros id nibh vulputate, id malesuada nunc ultrices.</div>
                        </div>
                        <div class="col-md-1 forum-info">
                            <span class="number"> 824 </span>
                            <small>Views</small>
                        </div>
                        <div class="col-md-1 forum-info">
                            <span class="number"> 266 </span>
                            <small>Posts</small>
                        </div>
                    </div>
                </div>

            </div>


        </div>
    </div>

</div>